[settings]
timeout = 3000

[relaychain]
chain = "paseo-local"
default_command = "polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true
[relaychain.nodes.node] # Configuration for the node's execution
args = ["--blocks-pruning", "256", "--state-pruning", "256"]


[[parachains]]
id = 2000
default_command = "./target/release/parachain-template-node"

[[parachains.collators]]
name = "collator-01"